### ISSUE TITLE
Release nat.nblast 1.6.5

### ISSUE THREAD

**Issue by jdmanton** [natverse/nat.nblast#37]
Prepare for release: 
 
* [x] Check that description is informative 
* [x] Check licensing of included files 
* [ ] `usethis::use_cran_comments()` 
* [x] `devtools::check()` 
* [x] `devtools::check_win_devel()` 
* [x] `rhub::check_for_cran()` 
* [ ] Polish pkgdown reference index 
 
Submit to CRAN: 
 
* [ ] `usethis::use_version('patch')` 
* [ ] Update `cran-comments.md` 
* [ ] `devtools::submit_cran()` 
* [ ] Approve email 
 
Wait for CRAN... 
 
* [ ] Accepted :tada: 
* [ ] `usethis::use_github_release()` 
* [ ] `usethis::use_dev_version()` 
* [ ] Update install instructions in README 
* [ ] Tweet

**Comment by jefferis** [comment]
@jdmanton nice checklist! Where are we on this?

**Comment by jefferis** [comment]
(it's on CRAN, right?)

**Comment by jdmanton** [comment]
> (it's on CRAN, right?)

Yes, I just forgot to close this.
